import Head from 'next/head';
import LoginForm from '@/components/login/loginForm';

const Profile: React.FC = () => {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-512-white.svg" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
      </Head>
    <main>
      <div className="flex justify-center items-center h-screen">
          <LoginForm />
      </div>
    </main>
    </>
  );
}

export default Profile;