import ShoppingCart from "@/components/cart/ShoppingCart";
import Navbar from "@/components/header/navbar";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { jwtDecode } from "jwt-decode";
import { useTranslation } from "next-i18next";
import Head from "next/head";

const Cart: React.FC = () => {
  const { t } = useTranslation();
  const router = useRouter();
  const [userId, setUserId] = useState<number>(0);
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    const token = localStorage.getItem("token");
    if (!token) {
      router.push("/login");
    } else {
      try {
        const decodedToken: any = jwtDecode(token);
        console.log(decodedToken);
        setUserId(decodedToken.userId);
      } catch (error) {
        console.error("Invalid token:", error);
        router.push("/login");
      } finally {
        setLoading(false);
      }
    }
  }, [router]);
  if (loading) {
    return (
      <div className="flex justify-center items-center h-64">
        <div className="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-gray-900"></div>
      </div>
    );
  }
  return (
    <>
      <Head>
        <title>{t("cart.title")}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-512-white.svg" />
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </Head>
      <Navbar type="cart"/>
      <main>
        {userId !== null ? (
          <ShoppingCart userId={userId} />
        ) : (
          <div>{t("cart.nouserid")}</div>
        )}
      </main>
    </>
  );
};
export const getServerSideProps = async (context: { locale: any }) => {
  const { locale } = context;
  return {
    props: {
      ...(await serverSideTranslations(locale ?? "en", [`common`])),
    },
  };
};
export default Cart;
