import RegisterForm from "@/components/register/registerForm"
import Head from "next/head";

const Register: React.FC = () => {
    return (
        <>
            <Head>
                <title>Register</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo-512-white.svg" />
                <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
            </Head>
            <main className="flex flex-col justify-center items-center h-screen">
                <p className="font-bold text-2xl mb-5">Register</p>
                <div>
                    <RegisterForm />
                </div>
            </main>
        </>
    );
}

export default Register;