import RegisterForm from "@/components/register/registerForm"
import Head from "next/head";
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useTranslation } from "next-i18next";

const Register: React.FC = () => {

    const { t } = useTranslation();

    return (
        <>
            <Head>
                <title>{t("register.register")}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo-512-white.svg" />
                <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
            </Head>
            <main className="flex flex-col justify-center items-center h-screen">
                <p className="font-bold text-2xl mb-5">{t("register.register")}</p>
                <div>
                    <RegisterForm />
                </div>
            </main>
        </>
    );
};

export const getServerSideProps = async (context: { locale: any; }) => {
    const { locale } = context;
    return {
        props: {
            ...(await serverSideTranslations(locale ?? "en", [`common`])),
        },
    };
}


export default Register;