import Navbar from "@/components/header/navbar";
import Main from "@/components/main/main";
import Head from "next/head";

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>User Bazaar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-512-white.svg" />
      </Head>
        <header>
          <Navbar />
        </header>
        <main className="w-full h-full px-5 ">
          <Main />
        </main>
    </>
  );
};

export default Home;
